# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-11 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0006_auto_20180227_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roundstats',
            options={'verbose_name_plural': 'round stats'},
        ),
        migrations.AlterModelOptions(
            name='scratch',
            options={'verbose_name_plural': 'scratches'},
        ),
        migrations.AlterModelOptions(
            name='tabsettings',
            options={'verbose_name_plural': 'tab settings'},
        ),
    ]
